ember-cli/ember-cli-update

package.json, src/get-project-version.js, test/integration/get-project-version-test.js
=> use semver to get lowest allowed version

bin/ember-cli-update.js, src/index.js
=> allow dist-tag latest or beta

README.md, src/args.js, src/get-tag-version.js, test/integration/get-tag-version-test.js
=> allow version hints

README.md, bin/ember-cli-update.js, src/args.js, src/command.js, src/get-project-version.js, src/index.js, test/unit/get-project-version-test.js
=> add --from option

README.md, bin/ember-cli-update.js, src/args.js, src/command.js, src/index.js
Closes #55
No logic here, just passes the option along to https://github.com/kellyselden/git-diff-apply
cc @rwjblue
=> add --ignore-conflicts option

README.md
=> mention ember init

README.md
Not finished. Just getting started.
Mentioned in #58.
=> start a git mergetool help section

.eslintrc.js, package.json
borrowed from https://github.com/kellyselden/git-diff-apply/pull/50
=> prevent accidental .only in tests

test/acceptance/ember-cli-update-test.js
=> remove `inherit` issue workaround code

test/acceptance/ember-cli-update-test.js
=> move to options hash in tests

bin/.eslintrc.js, bin/ember-cli-update.js, test/acceptance/ember-cli-update-test.js
Closes #65
borrowed from https://github.com/kellyselden/git-diff-apply/blob/master/test/acceptance/git-diff-apply-test.js#L195
=> add a dirty test

package.json
=> chore(package): update git-fixtures to version 0.7.2

README.md
Closes #66
I think this is as good as I can get it for now.
=> more explaining global vs command

package.json
=> fix(package): update git-diff-apply to version 0.3.1

package.json
=> chore(package): update eslint-config-sane to version 0.2.1

package.json, src/index.js, test/fixtures/local/my-addon/tests/dummy/app/controllers/application.js, test/fixtures/local/my-app/app/controllers/application.js, test/fixtures/merge/my-addon/tests/dummy/app/controllers/application.js, test/fixtures/merge/my-app/app/controllers/application.js
=> run ember-modules-codemod when necessary

README.md
=> Clarify explanation of how the addon works

test/acceptance/ember-cli-update-test.js, test/helpers/assertions.js, test/helpers/build-tmp.js
Closes #111
cc @rwjblue @kategengler
=> allow running in subdir

src/index.js, test/integration/index-test.js
=> handle no package.json

package.json, src/get-versions.js, src/index.js, src/utils.js, test/unit/get-versions-test.js
=> extract get-versions

src/get-project-version.js, src/index.js, test/integration/index-test.js, test/unit/get-project-version-test.js
=> require --from if glimmer < 0.6.3

.travis.yml, appveyor.yml
=> only test min and max node versions

README.md, bin/ember-cli-update.js, package.json, src/args.js, src/command.js, src/index.js, test/acceptance/ember-addon-test.js, test/acceptance/ember-cli-update-test.js
=> convert --ignore-conflicts to --resolve-conflicts

README.md
Totally understand if I should just be reading more carefully, but this would've read more clearly for me personally (ember installing for the first time).
=> Over clarifying usage

README.md, bin/ember-cli-update.js, package-lock.json, package.json, src/args.js, src/command.js, src/get-compare-url.js, src/index.js, src/utils.js, test/integration/index-test.js, test/unit/get-compare-url-test.js
=> add --compare-only option

appveyor.yml, test/acceptance/ember-addon-test.js
so allow failures until end of life (should still work) (fingers crossed!)
=> node 4 regressed hard on appveyor

src/run-codemods.js, test/acceptance/ember-cli-update-test.js, test/unit/run-codemods-test.js
=> add ember-qunit-codemod

README.md, bin/ember-cli-update.js, src/args.js, src/command.js, src/index.js, test/integration/index-test.js
=> add --list-codemods option

test/fixtures/codemod/latest-node/my-app/tests/acceptance/application-test-test.js, test/fixtures/codemod/latest-node/my-app/tests/integration/components/my-component-test.js
using ember-test-helpers-codemod node 6 as a test
=> add ember-test-helpers-codemod

src/run-codemods.js, test/unit/run-codemods-test.js
=> continue if one codemod errors

package.json
replace 'kellyselden' references with 'ember-cli' throughout the codebase.
=> replace kellyselden with ember-cli

README.md
=> document run codemod after updating

README.md
=> add some examples to the readme

appveyor.yml
10.3.0 is broken. Future versions may start working again.
=> remove locked node 10 windows version

bin/ember-cli-update.js, package-lock.json, package.json
=> Display notification when a newer version is available

test/integration/get-tag-version-test.js, test/integration/index-test.js, test/unit/compare-versions-test.js, test/unit/get-applicable-codemods-test.js, test/unit/get-versions-test.js, test/unit/run-codemod-test.js, test/unit/run-codemods-test.js
=> fix sinon.sandbox.create deprecation

README.md, bin/ember-cli-update.js, src/args.js, src/command.js, src/format-stats.js, src/index.js, test/integration/index-test.js
=> add --stats-only option

README.md, src/args.js
=> mention .ember-cli

src/index.js
Just fixes a small typo I spotted while running some code mods
=> Fix typo in message

.travis.yml, appveyor.yml
make sure we are using the bundled npx version and not the system one.
=> test local npx include

src/index.js
rawgit is shutting down, so lets change sooner rather than later
=> swap rawgit for githubusercontent

src/args.js, src/command.js
because my fingers are tired from typing it all the time :)
=> add `ccd` alias for `create-custom-diff`

test/integration/index-test.js
=> add lists codemods comment

bin/commands/bootstrap.js, src/bootstrap.js, test/acceptance/ember-cli-update-test.js
=> add bootstrap command

src/load-safe-blueprint-file.js, test/fixtures/blueprint/addon/legacy-app/local/ideal/my-app/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/merge/ideal/my-app/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/merge/no-state-file/my-app/ember-cli-update.json, test/fixtures/blueprint/app/legacy-app/local/my-app/ember-cli-update.json, test/fixtures/blueprint/app/legacy-app/merge/my-app/ember-cli-update.json, test/fixtures/blueprint/app/local-app/init/my-app/ember-cli-update.json, test/fixtures/blueprint/app/local-app/local/my-app/ember-cli-update.json, test/fixtures/blueprint/app/local-app/merge/my-app/ember-cli-update.json, test/fixtures/blueprint/app/npm-app/local/my-app/ember-cli-update.json, test/fixtures/blueprint/app/npm-app/merge/my-app/ember-cli-update.json, test/fixtures/blueprint/app/remote-app/local/my-app/ember-cli-update.json, test/fixtures/blueprint/app/remote-app/merge/my-app/ember-cli-update.json, test/fixtures/ember-cli-update-json/default/ember-cli-update.json, test/integration/load-safe-blueprint-file-test.js
=> add first schema version

src/get-start-and-end-commands.js, src/load-safe-default-blueprint.js, test/integration/load-safe-default-blueprint-test.js, test/unit/get-start-and-end-commands-test.js
=> replace `ember addon` with `ember new -b addon`

test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js, test/integration/index-test.js
https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/22
=> test notify-property-change codemod

src/index.js, test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js
test https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/23
=> try deprecate-merge codemod

src/index.js, test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js
=> try cp-property codemod for 3.8

src/index.js, test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js
=> Try cp-volatile codemod

src/index.js, test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js
https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/33
=> [FEAT] Add fpe-on codemod and fixtures

src/index.js, test/fixtures/codemod/latest-node/my-app/app/controllers/application.js, test/fixtures/codemod/local/my-app/app/controllers/application.js, test/fixtures/codemod/min-node/my-app/app/controllers/application.js
https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/34
=> [FEAT] Add fpe-computed codemod and fixtures

src/bootstrap.js, src/index.js, src/init.js, src/install.js
for future growth and refactoring
=> finish isDefaultBlueprint extraction

src/init.js, src/install.js, src/load-safe-default-blueprint.js, src/save-blueprint.js, src/save-default-blueprint.js, test/fixtures/blueprint/addon/legacy-app/local/ideal/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/merge/ideal/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/merge/no-state-file/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/init/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/local/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local/v0.0.1/files/config/ember-cli-update.json, test/fixtures/blueprint/app/local/v0.0.2/files/config/ember-cli-update.json, test/fixtures/ember-cli-update-json/default/config/ember-cli-update.json, test/integration/load-safe-default-blueprint-test.js, test/unit/save-blueprint-test.js, test/unit/save-default-blueprint-test.js
to prepare for running multiple blueprints at once with one as the base.
=> rename isPartial to isBaseBlueprint for now

README.md, bin/commands/default.js, src/args.js, src/command.js, src/index.js
=> expose --codemods-url option

test/acceptance/ember-cli-update-test.js
borrowed from https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/41
=> properly unregister listener

src/check-for-blueprint-updates.js, src/download-package.js, src/index.js, src/init.js, src/install.js, src/save.js, src/utils.js, test/integration/download-package-test.js
since a package can contain many blueprints
=> refactor downloadBlueprint => downloadPackage

src/check-for-blueprint-updates.js, src/index.js, test/integration/check-for-blueprint-updates-test.js
for future formatting involving package name as well as blueprint name
=> include packageName in checkForBlueprintUpdates

package-lock.json
https://github.com/broccolijs/node-symlink-or-copy/issues/43
=> new lockfile for symlink-or-copy update

src/get-start-and-end-commands.js, test/fixtures/custom/addon/local/my-custom-addon/README.md, test/fixtures/custom/addon/local/my-custom-addon/index.js, test/fixtures/custom/addon/local/my-custom-addon/package.json, test/fixtures/custom/addon/merge/my-custom-addon/CONTRIBUTING.md, test/fixtures/custom/addon/merge/my-custom-addon/README.md, test/fixtures/custom/addon/merge/my-custom-addon/package.json, test/unit/get-start-and-end-commands-test.js
=> support scoped projects

test/acceptance/ember-cli-update-test.js
boilerplate-update covers this
=> remove subDir test

config/ember-cli-update.json, src/load-safe-blueprint-file.js, test/fixtures/addon/merge/my-addon/tests/dummy/config/ember-cli-update.json, test/fixtures/app/init/my-app/config/ember-cli-update.json, test/fixtures/app/merge/my-app/config/ember-cli-update.json, test/fixtures/app/reset/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/local/ideal/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/legacy-app/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/npm-app/local/my-app/config/ember-cli-update.json, test/fixtures/blueprint/addon/npm-app/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/legacy-app/local/my-app/config2/ember-cli-update.json, test/fixtures/blueprint/app/legacy-app/merge/my-app/config2/ember-cli-update.json, test/fixtures/blueprint/app/local-app/init/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/local/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/reset/local/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/local-app/reset/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/npm-app/local/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/npm-app/merge/my-app/config/ember-cli-update.json, test/fixtures/blueprint/app/remote-app/local/my.app/config/ember-cli-update.json, test/fixtures/blueprint/app/remote-app/merge/my.app/config/ember-cli-update.json, test/fixtures/ember-cli-update-json/default/config/ember-cli-update.json, test/fixtures/ember-cli-update-json/normal/ember-cli-update.json, test/fixtures/ember-cli-update-json/old/ember-cli-update.json, test/fixtures/ember-cli-update-json/unexpected-version/ember-cli-update.json, test/fixtures/glimmer/merge/glimmer-app/config/ember-cli-update.json, test/integration/load-safe-blueprint-file-test.js, test/integration/save-blueprint-file-test.js
=> schemaVersion semver

src/index.js, src/init.js
=> deprecate --resolve-conflicts

src/command.js
=> deprecate ember addon capability

src/index.js, test/fixtures/ember-cli-update-json/addon/config/ember-cli-update.json, test/integration/index-test.js
=> failing test for out of sync ember-cli version

.github/workflows/ci.yml, config/ember-cli-update.json, package-lock.json, package.json
Reverts ember-cli/ember-cli-update#1069
=> Revert "Update dependency @kellyselden/node-template to v1.3.0"

.github/workflows/ci.yml
=> disable latest node testing in CI

CHANGELOG.md, RELEASE.md, package-lock.json, package.json
We already have a github action to do a release but I've added release-it using `npm init rwjblue-release-it-setup` to make tagging a release easier 👍
=> Setup release-it

.github/workflows/ci.yml, .github/workflows/publish.yml, package.json
This work is supported by the [Mainmatter Ember Initiative](https://mainmatter.com/ember-initiative/).
=> Drop support for Node < 20
