appveyor.yml

since they run synchronously, it only slowed them down to have them split out (double npm install).

remove jobs from appveyor

---

src/get-package-version.js
src/index.js
test/acceptance/ember-cli-update-test.js

https://github.com/kellyselden/ember-cli-update/issues/116

[PATCH] Throw error for non Ember CLI project

---

package.json
src/index.js

It searches the various .bin directories correctly to more reliably find the ember-modules-codemod binary
Closes #184 #186

Use execa to launch ember-modules-codemod

---

test/acceptance/ember-addon-test.js

npm 5 + windows will alter the line endings of the package.json. This messes with our dirty checking.

fix npm 5 windows testing issue

---

src/get-tag-version.js
src/index.js

Allow glimmer project to update to latest @glimmer/blueprint without having to specify --to option

Fix incorrect tag version for glimmer projects

---

README.md

`Error: Command failed: git apply /var/folders/59/.../T/tmp-.../file.patch error: unrecognized input `
In the .gitconfig Having color ui set to alway caused the above error.
[color]
ui = always
Change that to:
[color]
ui = auto
https://stackoverflow.com/questions/37347350/all-git-patches-i-create-throw-fatal-unrecognized-input
Sorry, @kellyselden I thought I had pushed an update to #236 a while ago.

Adding troubleshooting tips to the readme

---

src/run-codemods.js

Would resolve: https://github.com/ember-cli/ember-cli-update/issues/255

Add es5-getter-ember-codemod to list of codemods to run

---

src/get-applicable-codemods.js
src/get-codemods.js
src/get-node-version.js
src/utils.js
test/unit/get-applicable-codemods-test.js
test/unit/get-dry-run-stats-test.js
test/unit/run-codemods-test.js

This will allow us to merge https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/1 without waiting for node 4 end-of-life.

add node version constraint to codemods

---

.travis.yml
README.md
appveyor.yml

Hi! Can't wait to use this repo more. 
At a quick glance, it looks like Greenkeeper is no longer used. This PR removes Greenkeeper refs.

chore(update): removes Greenkeeper ref

---

README.md
bin/ember-cli-update.js
package-lock.json
package.json
src/args.js
src/command.js
src/get-start-and-end-commands.js
src/index.js
src/npx.js
test/acceptance/ember-cli-update-test.js
test/unit/get-start-and-end-commands-test.js

Closes #125
Use your own versions of apps instead of the output repo's. The intent is to mix with your own .ember-cli file to get your own catered diffs. This is much slower (and more error-prone if it is a really old version) than the normal way to update.
```
ember-cli-update --custom-remote
```
@rwjblue @rwwagner90 @Turbo87 does this solve your yarn issues?

add createCustomDiff option

---

src/get-project-options.js
test/unit/get-project-options-test.js

This change allows ember-cli/glimmer to be specified as either a dependency
or devDependency of the project being updated. Currently, `ember-cli-update`
throws an error in some instances, since it is only checking devDependencies.

Support Detection of Ember/Glimmer apps as dependencies

---

src/get-package-version.js
test/unit/get-package-version-test.js

Currently we only check `devDependencies`, so if the requested package is in `dependencies`, an error is thrown. We should be able to find it regardless.

Get package version if dependency

---

src/get-package-version.js
test/unit/get-package-version-test.js

don't throw for cases of `"ember-cli": "",`

---

src/index.js
test/fixtures/codemod/latest-node/my-app/app/routes/index.js
test/fixtures/codemod/local/my-app/app/routes/index.js
test/fixtures/codemod/min-node/my-app/app/routes/index.js

https://github.com/ember-cli/ember-cli-update-codemods-manifest/pull/24

Test deprecate-router-events codemod

---

src/index.js
test/fixtures/codemod/latest-node/my-app/app/controllers/application.js
test/fixtures/codemod/local/my-app/app/controllers/application.js
test/fixtures/codemod/min-node/my-app/app/controllers/application.js

try cp-property-map codemod from ember-3x-codemods

---

src/parse-blueprint-package.js
test/integration/parse-blueprint-package-test.js

Previously we had logic to detect the difference between a subdir with the name "foo" and an npm package "foo". This prevented a self referencings blueprints "." because it would be considered a subdir. Now we avoid this problem by requiring local blueprints start with ".". So "foo" => "./foo".

require local blueprints start with .

---

test/acceptance/ember-addon-test.js
test/acceptance/ember-cli-update-test.js
test/integration/check-for-blueprint-updates-test.js
test/integration/codemods-test.js
test/integration/compare-test.js
test/integration/download-package-test.js
test/integration/index-test.js
test/integration/init-test.js
test/integration/install-test.js
test/integration/overwrite-blueprint-files-test.js
test/integration/reset-test.js
test/integration/save-test.js
test/integration/stats-test.js

I've been using this convention lately. `e3` is a more concise way to say seconds than `* 1000`.

use `e3` syntax in tests to mean seconds

---

src/get-start-and-end-commands.js
test/unit/get-start-and-end-commands-test.js

This fixes the use of ember-cli-update with the v2 addon blueprint https://github.com/embroider-build/addon-blueprint
I know there are a few tests to fix but it shows the main things that needed to change: 
- use latest ember-cli for custom blueprints because it was locking down to 3.16 before because of the `lastNode8Version`
- remove `-sb` which I'm assuming was `--skip-bower`
I'm going to get tests passing on this but I'm wondering if now is a good time to remove the `lastNode8Version` since it has the comment `// remove when node 8 is dropped` which has already happened 🤔

Fix custom blueprints

---

src/get-start-and-end-commands.js
src/index.js

Fixes https://github.com/ember-cli/ember-cli-update/issues/1248

fix projectName if there is no package.json name

---

src/get-start-and-end-commands.js
test/unit/get-start-and-end-commands-test.js

I must have missed these. We recently dropped support for legacy node versions and this bit of code was still referencing an ancient one.
---
This work is supported by the [Mainmatter Ember Initiative](https://mainmatter.com/ember-initiative/).

Purge Node 8 related code

---

docs/upgrading-past-6-7.md
src/index.js

We tried automating this, ember-cli-update is too entangled to do so. Needs a link to documentation.

Warn users trying to upgrade past 6.7.0 - i.e. don't auto upgrade them to Vite
